import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Search-player',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/bg.png" as="image" />
        <link rel="preload" href="/title.png" as="image" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
