import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<link rel="preload" href="/bg.png" as="image" />
				<link rel="preload" href="/title.png" as="image" />
				<link rel="preload" href="/splashScreen/bg.png" as="image" />
				<link rel="preload" href="/splashScreen/title.png" as="image" />
			</head>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
